apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfonlaltinn
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: tt02.altinn.no
        - host: pdl-api.dev-fss-pub.nais.io
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        diskAutoresize: true
        databases:
          - name: syfonlaltinn
        tier: db-f1-micro
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  envFrom:
    - secret: syfonlaltinn-secret
  secureLogs:
    enabled: true
  env:
    - name: ALTINN_DOWNLOAD_QUEUE_URL
      value: https://tt02.altinn.no/ArchiveExternal/DownloadQueueExternalBasic.svc
    - name: ALTINN_PREFILL_URL
      value: https://tt02.altinn.no/ServiceEngineExternal/PrefillBasic.svc
    - name: KAFKA_CLIENT_ID
      value: syfonlaltinn
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
