apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfonlaltinn
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: www.altinn.no
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        diskAutoresize: true
        databases:
          - name: syfonlaltinn
  kafka:
    pool: nav-prod
  vault:
    enabled: false
  ingresses:
    - "https://syfonlaltinn.intern.nav.no"
  webproxy: true
  envFrom:
    - secret: syfonlaltinn-secret
  env:
    - name: ALTINN_DOWNLOAD_QUEUE_URL
      value: https://www.altinn.no/ArchiveExternal/DownloadQueueExternalBasic.svc
    - name: KAFKA_CLIENT_ID
      value: syfonlaltinn
